name: validator
description: "Form validators."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/intl
  intl: 0.19.0
  # https://pub.dev/packages/mime
  mime: 2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/flutter_lints
  flutter_lints: 5.0.0
